// Favourites
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const REMOVE_FAVOURITES = 'REMOVE_FAVOURITES';
export const INITIALIZE_FAVOURITES = 'INITIALIZE_FAVOURITES';
export const PURGE_FAVOURITES = 'PURGE_FAVOURITES';

// Home
export const SET_HOME_PROFILE = 'SET_HOME_PROFILE';
export const RESET_HOME_PROFILE = 'RESET_HOME_PROFILE';

// Navigation
export const CHANGE_CONTEXT_ID = 'CHANGE_CONTEXT_ID';
export const CHANGE_PARENT = 'CHANGE_PARENT';
export const CONSUME_HOME_TAB = 'CONSUME_HOME_TAB';

// Peers
export const REQUEST_PEERS = 'REQUEST_PEERS';
export const RECEIVE_PEERS = 'RECEIVE_PEERS';
export const RECEIVE_EMPTY_PEERS = 'RECEIVE_EMPTY_PEERS';

// Player Heroes
export const REQUEST_HEROES = 'REQUEST_HEROES';
export const RECEIVE_HEROES = 'RECEIVE_HEROES';
export const RECEIVE_EMPTY_HEROES = 'RECEIVE_EMPTY_HEROES';

// Player Matches
export const REQUEST_MATCHES = 'REQUEST_MATCHES';
export const RECEIVE_MATCHES = 'RECEIVE_MATCHES';
export const RECEIVE_EMPTY_MATCHES = 'RECEIVE_EMPTY_MATCHES';
export const CHANGE_SORTED_BY = 'CHANGE_SORTED_BY';

// Player Overview
export const REQUEST_OVERVIEW = 'REQUEST_OVERVIEW';
export const RECEIVE_OVERVIEW = 'RECEIVE_OVERVIEW';
export const RECEIVE_EMPTY_OVERVIEW = 'RECEIVE_EMPTY_OVERVIEW';
export const REQUEST_WL = 'REQUEST_WL';
export const RECEIVE_WL = 'RECEIVE_WL';
export const RECEIVE_EMPTY_WL = 'RECEIVE_EMPTY_WL';

// Player Search
export const REQUEST_PLAYERS = 'REQUEST_PLAYERS';
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS';
export const RECEIVE_EMPTY_PLAYERS = 'RECEIVE_EMPTY_PLAYERS';

// Records
export const REQUEST_RECORDS = 'REQUEST_RECORDS';
export const RECEIVE_RECORDS = 'RECEIVE_RECORDS';
export const RECEIVE_EMPTY_RECORDS = 'RECEIVE_EMPTY_RECORDS';

// Settings
export const CHANGE_THEME = 'CHANGE_THEME';